import type { TripPlan } from "./types";

export const sampleTripPlan: TripPlan = {
  city: "Taipei",
  start_date: "2026-06-01",
  end_date: "2026-06-03",
  overall_suggestions:
    "Keep mornings for outdoor sights, use public transit between districts, and leave flexible time for food stops.",
  budget: {
    total_attractions: 900,
    total_hotels: 4800,
    total_meals: 2700,
    total_transportation: 760,
    total: 9160,
  },
  weather_info: [
    {
      date: "2026-06-01",
      day_weather: "Cloudy",
      night_weather: "Light rain",
      day_temp: 29,
      night_temp: 24,
      wind_direction: "East",
      wind_power: "Level 2",
    },
    {
      date: "2026-06-02",
      day_weather: "Sunny intervals",
      night_weather: "Cloudy",
      day_temp: 31,
      night_temp: 25,
      wind_direction: "South",
      wind_power: "Level 2",
    },
    {
      date: "2026-06-03",
      day_weather: "Showers",
      night_weather: "Cloudy",
      day_temp: 28,
      night_temp: 24,
      wind_direction: "South East",
      wind_power: "Level 3",
    },
  ],
  routes: [
    {
      day_index: 0,
      from: "Chiang Kai-shek Memorial Hall",
      to: "Taipei 101",
      transportation: "MRT",
      distance_text: "5.2 km",
      duration_text: "22 min",
      map_url:
        "https://www.google.com/maps/dir/Chiang+Kai-shek+Memorial+Hall/Taipei+101",
      notes: "Use the red line toward Taipei 101 / World Trade Center.",
    },
    {
      day_index: 1,
      from: "National Palace Museum",
      to: "Dihua Street",
      transportation: "Bus + MRT",
      distance_text: "8.4 km",
      duration_text: "42 min",
      map_url:
        "https://www.google.com/maps/dir/National+Palace+Museum/Dihua+Street",
      notes: "Keep this transfer after lunch to avoid morning museum crowds.",
    },
    {
      day_index: 2,
      from: "Beitou Hot Spring Museum",
      to: "Yangmingshan National Park",
      transportation: "Bus",
      distance_text: "9.6 km",
      duration_text: "55 min",
      map_url:
        "https://www.google.com/maps/dir/Beitou+Hot+Spring+Museum/Yangmingshan+National+Park",
      notes: "Mountain buses can be slower in the afternoon.",
    },
  ],
  days: [
    {
      date: "2026-06-01",
      day_index: 0,
      description: "Arrival, classic Taipei landmarks, and an easy night market.",
      transportation: "Public transit",
      accommodation: "Economy hotel",
      hotel: {
        name: "CityInn Hotel Taipei Station Branch",
        address: "Taipei Main Station area",
        price_range: "NT$1,800-2,400",
        rating: 4.2,
        distance: "Near MRT and rail connections",
        type: "Economy hotel",
        estimated_cost: 1800,
      },
      attractions: [
        {
          name: "Chiang Kai-shek Memorial Hall",
          address: "No. 21, Zhongshan S Rd, Zhongzheng District",
          location: { longitude: 121.5198, latitude: 25.0346 },
          visit_duration: 90,
          description: "Large civic square, gardens, and cultural halls.",
          category: "History and culture",
          rating: 4.5,
          ticket_price: 0,
        },
        {
          name: "Taipei 101",
          address: "No. 7, Section 5, Xinyi Rd, Xinyi District",
          location: { longitude: 121.5654, latitude: 25.0339 },
          visit_duration: 120,
          description: "Iconic tower, shopping, and city views.",
          category: "Landmark",
          rating: 4.6,
          ticket_price: 600,
        },
      ],
      meals: [
        {
          type: "breakfast",
          name: "Local breakfast shop",
          description: "Soy milk, egg pancake, and rice roll.",
          estimated_cost: 120,
        },
        {
          type: "lunch",
          name: "Taipei 101 food court",
          description: "Convenient lunch near the observation deck.",
          estimated_cost: 350,
        },
        {
          type: "dinner",
          name: "Raohe Night Market",
          description: "Pepper buns, oyster vermicelli, and bubble tea.",
          estimated_cost: 450,
        },
      ],
    },
    {
      date: "2026-06-02",
      day_index: 1,
      description: "Museum, old streets, and riverside sunset.",
      transportation: "Public transit",
      accommodation: "Economy hotel",
      hotel: {
        name: "CityInn Hotel Taipei Station Branch",
        address: "Taipei Main Station area",
        price_range: "NT$1,800-2,400",
        rating: 4.2,
        distance: "Central base for MRT trips",
        type: "Economy hotel",
        estimated_cost: 1800,
      },
      attractions: [
        {
          name: "National Palace Museum",
          address: "No. 221, Sec 2, Zhishan Rd, Shilin District",
          location: { longitude: 121.5485, latitude: 25.1024 },
          visit_duration: 150,
          description: "Major museum for Chinese art and historical artifacts.",
          category: "Art",
          rating: 4.6,
          ticket_price: 350,
        },
        {
          name: "Dihua Street",
          address: "Dihua St, Datong District",
          location: { longitude: 121.5101, latitude: 25.0586 },
          visit_duration: 100,
          description: "Historic shops, tea houses, snacks, and old architecture.",
          category: "Food",
          rating: 4.3,
          ticket_price: 0,
        },
      ],
      meals: [
        {
          type: "breakfast",
          name: "Hotel area cafe",
          description: "Light breakfast before the museum.",
          estimated_cost: 180,
        },
        {
          type: "lunch",
          name: "Shilin local noodles",
          description: "Simple local lunch near the museum route.",
          estimated_cost: 260,
        },
        {
          type: "dinner",
          name: "Dadaocheng tea house",
          description: "Tea and small dishes around Dihua Street.",
          estimated_cost: 520,
        },
      ],
    },
    {
      date: "2026-06-03",
      day_index: 2,
      description: "Nature and hot spring district before departure.",
      transportation: "Public transit",
      accommodation: "Economy hotel",
      hotel: {
        name: "CityInn Hotel Taipei Station Branch",
        address: "Taipei Main Station area",
        price_range: "NT$1,800-2,400",
        rating: 4.2,
        distance: "Easy luggage pickup before departure",
        type: "Economy hotel",
        estimated_cost: 1200,
      },
      attractions: [
        {
          name: "Beitou Hot Spring Museum",
          address: "No. 2, Zhongshan Rd, Beitou District",
          location: { longitude: 121.5077, latitude: 25.1368 },
          visit_duration: 75,
          description: "Compact museum in a historic bathhouse.",
          category: "Leisure",
          rating: 4.2,
          ticket_price: 0,
        },
        {
          name: "Yangmingshan National Park",
          address: "Yangmingshan, Beitou District",
          location: { longitude: 121.5477, latitude: 25.1553 },
          visit_duration: 180,
          description: "Mountain scenery, trails, and seasonal flowers.",
          category: "Nature",
          rating: 4.5,
          ticket_price: 0,
        },
      ],
      meals: [
        {
          type: "breakfast",
          name: "Taipei Main Station bakery",
          description: "Quick breakfast before Beitou.",
          estimated_cost: 150,
        },
        {
          type: "lunch",
          name: "Beitou hot spring set meal",
          description: "Warm local meal after the museum.",
          estimated_cost: 420,
        },
        {
          type: "dinner",
          name: "Station bento",
          description: "Easy meal before leaving Taipei.",
          estimated_cost: 250,
        },
      ],
    },
  ],
};
